chain = "Custom"

[pbs]
port = 18550
relay_check = true
timeout_get_header_ms = 950
timeout_get_payload_ms = 4000
timeout_register_validator_ms = 3000
skip_sigverify = true
min_bid_eth = 0.0

late_in_slot_time_ms = 2000

[[relays]]
id = "preconf-relay"
url = "http://0xa9e9cff900de07e295a044789fd4bdb6785eb0651ad282f9e76d12afd87e75180bdd64caf2e315b815d7322bd31ab48a@host.docker.internal:4040"
enable_timing_games = false
target_first_request_ms = 200
frequency_get_header_ms = 300

[signer]
[signer.loader]
key_path = "./keys.example.json"

[metrics]
prometheus_config = "./docker/prometheus.yml"
use_grafana = true

[[modules]]
id = "PRECONF"
type = "preconf"
docker_image = "test_preconf"
beacon_nodes = ["http://host.docker.internal:60869"]
chain_id = 3151908
